import { fromEvent, map, tap } from "rxjs";

const texto = document.createElement('div');
texto.innerHTML = `
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam a nulla tempor, faucibus libero in, elementum nulla. Vestibulum congue, quam at condimentum aliquet, nulla elit faucibus tellus, in placerat felis sapien interdum dui. Integer aliquet at neque eget elementum. Integer eleifend dictum finibus. Duis sollicitudin ornare massa, eu venenatis ante congue in. Vestibulum ac ex sed lorem facilisis finibus quis ac odio. Vestibulum eget augue viverra, pulvinar ipsum non, malesuada elit. Morbi pulvinar metus a augue ullamcorper porta. Fusce ipsum diam, vulputate vitae ultricies id, pellentesque at tortor. Fusce nunc lorem, euismod porta laoreet et, mattis porttitor mauris. Donec faucibus libero et viverra varius. Nulla blandit sem metus, ut blandit orci finibus eu. Phasellus bibendum lorem dolor, non luctus lacus eleifend vel.
<br />
Morbi sed mi dictum, molestie metus eget, semper felis. Vivamus pretium magna id metus auctor, a rhoncus magna porttitor. Donec lacinia finibus dui et commodo. Fusce neque purus, dignissim scelerisque condimentum a, tincidunt ut ipsum. Nulla ullamcorper dictum ligula eget pretium. Nunc pharetra, sapien ut sodales feugiat, lectus enim mattis sem, vitae dictum mauris tellus a augue. Donec non vulputate orci, ut convallis nisi. Aliquam risus tortor, fermentum non rhoncus in, porttitor ac ipsum. Suspendisse lobortis semper ex, non pharetra odio suscipit nec. Sed in nisi eu lacus fermentum hendrerit ut a sapien.
<br />
Aliquam lacinia mi at velit auctor lobortis. Maecenas sagittis, urna vitae porttitor aliquet, nunc enim consectetur mauris, nec semper purus eros id felis. Nulla placerat eu nibh quis tristique. Suspendisse eu leo efficitur, laoreet metus quis, aliquet turpis. Nulla convallis erat a lacus ultricies condimentum. Proin ac est nisl. Maecenas at mi orci. Sed leo felis, sollicitudin ac eros nec, molestie fermentum est. Proin pulvinar a elit vel ultrices. Donec eu sapien non diam condimentum auctor. Fusce sollicitudin erat ac augue egestas dapibus.
<br />
Fusce efficitur nisl in interdum consectetur. Suspendisse potenti. Ut varius volutpat turpis. Quisque eget velit sapien. Aliquam aliquet iaculis turpis, ut pulvinar lectus tincidunt sit amet. Integer eu massa id nisl posuere porttitor. Sed vitae dui eget massa facilisis congue sed et ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean vel ultricies tortor. Pellentesque sed ligula auctor, pulvinar dui sit amet, finibus eros. Ut in molestie metus. In sit amet sapien et eros rhoncus auctor. Vestibulum efficitur hendrerit luctus. Nunc sed dictum elit. Suspendisse eget tempus justo, sit amet placerat nulla. Nam sit amet ante dui.
<br />
Suspendisse potenti. Proin ornare libero ac odio consequat, in ullamcorper diam egestas. Duis quis ligula ac purus suscipit porta eu a turpis. Phasellus quis leo aliquet, imperdiet nisl suscipit, placerat dolor. Mauris a nisi imperdiet, mollis lacus vitae, mattis lectus. Donec gravida, augue mattis maximus placerat, sapien nibh consequat metus, fermentum viverra augue diam vitae risus. Cras non auctor turpis. Vivamus a mi sagittis, facilisis quam quis, rutrum neque. Praesent pretium enim eu condimentum maximus. Ut iaculis eget urna et volutpat. Donec sit amet auctor nulla, vel vestibulum eros. Etiam ullamcorper maximus est, sed consequat sapien efficitur nec. Nulla arcu arcu, commodo accumsan dui at, porta posuere diam. Proin ullamcorper mattis ligula in hendrerit. Suspendisse auctor, neque quis iaculis tempus, orci quam sollicitudin lorem, non egestas enim felis egestas nulla.
<br />
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mattis, ligula quis pharetra cursus, mauris arcu lacinia justo, ut pellentesque turpis orci ac elit. Pellentesque suscipit lorem quis sem euismod, in tristique ligula luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce lobortis eros nisl, id volutpat lacus commodo et. Aliquam maximus, neque sit amet malesuada molestie, lacus erat feugiat nisi, et efficitur velit leo at risus. Vivamus rutrum nulla ut risus consequat, quis posuere enim viverra. Quisque sit amet facilisis tellus. Proin mattis, sapien at rutrum ullamcorper, erat turpis dictum metus, nec condimentum ipsum nulla ac lectus. Aenean ac nisi consectetur, aliquam nunc eget, fringilla velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus cursus lacus mollis lacus condimentum, eu porttitor arcu molestie. In hendrerit, ex id congue scelerisque, tellus ante condimentum diam, et auctor nisi sem sed urna.
<br />
Sed euismod rhoncus mi in bibendum. Suspendisse nec libero varius, semper ante eleifend, ornare lectus. Donec rutrum auctor pellentesque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse ultricies, massa non mollis posuere, dui mauris egestas arcu, eu scelerisque augue ex quis nunc. Ut eu semper ex, nec blandit ligula. Ut sit amet elit odio. Cras mauris quam, luctus quis euismod vel, vehicula sed sapien. Donec nec nulla turpis. Mauris bibendum convallis vulputate. Suspendisse molestie sapien neque, non dapibus neque venenatis sed. Integer ultricies dui at erat cursus dictum. Etiam vel purus pulvinar, auctor orci nec, lobortis turpis. Donec quis dui tincidunt, mattis lectus et, faucibus sapien. Quisque vitae pharetra ipsum, a eleifend felis.
<br />
Mauris dignissim elementum urna, nec sagittis massa. Nam dapibus egestas ipsum, nec lobortis nulla. Curabitur vel elit ornare, sodales magna quis, convallis dui. Phasellus scelerisque justo quis consectetur iaculis. Fusce non imperdiet augue. Sed condimentum ut tellus a scelerisque. Nullam pellentesque ut mi eget laoreet. Nulla placerat erat tristique nunc tincidunt consequat. Ut sed mollis nisl, vitae condimentum augue.
<br />
Praesent venenatis rhoncus finibus. Praesent venenatis, felis at lacinia condimentum, massa odio rutrum felis, quis placerat felis mauris vitae tortor. Vestibulum quis purus a nisi egestas fringilla. Sed dui metus, pulvinar ut viverra et, vehicula eget lectus. Curabitur quis metus ac orci interdum aliquet. Cras placerat elementum tristique. Curabitur risus elit, fringilla sed consectetur ultricies, consectetur rutrum erat. Quisque lobortis ac turpis eu posuere. Nunc volutpat, nisl in posuere dictum, dui ante laoreet urna, eu facilisis dui dui non dui. Nullam nibh quam, blandit sed condimentum ut, interdum sit amet libero. Nam euismod, nulla non suscipit lacinia, tellus nulla ornare arcu, scelerisque ornare magna massa non libero. Phasellus suscipit quam nec egestas dapibus. Cras eget pulvinar arcu, ut bibendum ante. Aenean posuere augue nec arcu elementum, id sagittis dui efficitur.
<br />
Maecenas id condimentum mi. Fusce vel pretium libero. Proin tristique sagittis lacinia. Sed vestibulum vehicula dui, ac vulputate mi. Duis et purus non ex pellentesque iaculis. In id elit diam. Sed id ante non augue vehicula suscipit ut sit amet ligula. Aenean hendrerit, sapien in vestibulum sollicitudin, massa purus egestas sapien, nec imperdiet arcu metus vitae mi. Etiam nec mollis elit. Nulla eget massa vulputate, faucibus diam a, fermentum mi.
<br />
Integer id dui ante. Curabitur ante dui, tempus sed egestas nec, pellentesque dignissim augue. Praesent sapien libero, ullamcorper vitae ullamcorper nec, euismod eu felis. Nulla fringilla sodales mauris, sed luctus erat viverra at. Ut a luctus lacus, ac sodales risus. Mauris porttitor mauris at luctus maximus. Maecenas eu mi risus. Proin eget lacinia ex. Ut feugiat porta turpis nec pulvinar. Cras quis imperdiet neque. Nulla tristique accumsan tellus ullamcorper faucibus. In rutrum elit eget purus aliquet viverra.
<br />
Nunc vitae dictum est. Praesent et justo quam. Mauris tincidunt eu ex eu luctus. Fusce volutpat dignissim erat a tincidunt. Aliquam eget molestie mauris. Etiam nec facilisis quam. Phasellus facilisis metus lacinia interdum consequat.
<br />
Donec mattis tristique elit, a accumsan risus. Mauris porta dignissim congue. Sed quis pellentesque velit. Integer metus sem, finibus eget erat sed, molestie tincidunt ex. Ut justo mi, efficitur a odio sed, luctus euismod ante. Nullam eu lorem rutrum, eleifend ipsum non, maximus sapien. Maecenas pharetra elit ac eleifend hendrerit. Maecenas eget justo viverra nisi mollis volutpat. Integer in orci sem. Nullam tempus aliquet ante id ornare. Duis et velit ut magna pellentesque pulvinar.
<br />
Donec sed quam sit amet nunc aliquet congue. Donec faucibus posuere maximus. Phasellus volutpat risus eu interdum fermentum. Phasellus neque mi, rhoncus ac eros interdum, facilisis sagittis leo. Fusce sit amet metus sit amet massa ullamcorper porttitor. Integer tincidunt in nisi vel ultrices. Vestibulum vitae laoreet leo. Ut finibus, turpis eu placerat tincidunt, tortor risus porta sem, sit amet dignissim justo purus id quam. Maecenas vel metus non libero fringilla posuere in ut lectus. Pellentesque varius vehicula sapien, non rutrum eros mattis sit amet. Nulla nec quam eros. Pellentesque accumsan vel nunc et ornare. Morbi mollis purus libero, sit amet tempus ligula fringilla in.
<br />
Sed a odio tincidunt, sollicitudin nisl non, suscipit libero. Vestibulum sit amet lacus in enim interdum vestibulum. Aliquam ac consectetur augue. Suspendisse fermentum nisl quis lacus semper luctus. Proin sit amet ultricies libero. Duis non ante at elit aliquet blandit. Suspendisse pulvinar pulvinar purus, ut malesuada elit sagittis vel. Sed vehicula consectetur nunc posuere varius. Ut dapibus porttitor metus, in iaculis odio dapibus non. Etiam dignissim vitae metus ac rhoncus. Nunc ac quam sed nibh finibus tempus. Nulla dignissim nibh metus, ac maximus augue consequat quis.
<br />
Maecenas ullamcorper lorem at convallis varius. Phasellus blandit arcu eu commodo placerat. Curabitur luctus erat ut erat hendrerit fringilla. Sed sed lobortis elit, vel mattis metus. Curabitur odio lacus, auctor porttitor eleifend id, venenatis a nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec nunc purus, vestibulum vel vestibulum at, faucibus ut quam. Sed ac quam in lacus ullamcorper tincidunt vitae a ante. Aenean tempus dapibus risus in tristique. Sed facilisis, sapien vel hendrerit laoreet, odio purus pellentesque ipsum, a iaculis augue tortor sit amet purus. Praesent ipsum risus, luctus mollis nunc ultrices, tincidunt bibendum magna. Donec lacinia quam vitae blandit mattis. Morbi ut luctus enim. Nunc malesuada ipsum in diam pulvinar ornare. Nunc bibendum, enim ut tempor tempus, justo mauris faucibus massa, ac condimentum erat sapien in sem.
<br />
Aliquam facilisis pulvinar massa, quis porttitor enim placerat at. Nam pharetra bibendum finibus. Etiam velit orci, rutrum sed nisi vel, suscipit euismod sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc ac sapien vel orci posuere blandit. Suspendisse maximus vulputate lacus, quis rutrum dui. In placerat arcu ut finibus porta. Phasellus vel odio faucibus, convallis arcu pulvinar, fermentum leo.
<br />
Duis dictum magna sit amet ipsum semper consequat. Aliquam erat volutpat. Ut faucibus luctus justo nec consectetur. Donec ipsum dui, tincidunt sed augue sed, semper blandit elit. Cras ullamcorper ligula a justo maximus, ac mattis metus gravida. Nulla ultricies mauris eros, non laoreet est porta vitae. Maecenas turpis ipsum, convallis ac interdum in, fringilla in nulla. Vivamus vitae ante blandit, porta libero eu, mattis sapien. Pellentesque consectetur eget risus et lobortis. Phasellus nec tortor in lectus iaculis elementum ac ultricies risus. Sed ut est tincidunt, lobortis leo ac, interdum risus. Curabitur vel sem at diam mollis iaculis vel eu leo. Pellentesque nibh ex, dictum a elementum quis, mattis vitae lorem.
<br />
Vestibulum posuere ullamcorper nunc, at sollicitudin justo dapibus eget. Fusce congue lacus eget sem posuere viverra. Mauris quis vehicula dolor, sollicitudin cursus est. Donec nunc lectus, pretium nec ante sed, ornare tempor mauris. Pellentesque urna velit, malesuada dictum nulla id, pulvinar imperdiet magna. Aenean non lorem rhoncus mi volutpat vestibulum. Nunc quis finibus elit. Nulla elementum leo non ante cursus commodo et quis purus.
<br />
Integer tincidunt nec quam vitae viverra. Fusce commodo ultrices metus sit amet convallis. Aenean ultricies non ante vel mollis. Curabitur vel tortor ipsum. Proin interdum magna sit amet odio porttitor, vel vulputate felis fermentum. Etiam sodales ut magna vitae porta. Maecenas enim nulla, porta maximus mauris vel, interdum facilisis magna. Mauris maximus euismod ornare. In hac habitasse platea dictumst. Praesent elementum, magna id aliquet commodo, velit dolor scelerisque turpis, sit amet convallis purus libero ut diam. Curabitur laoreet finibus lacus. Donec vulputate porttitor tellus. Sed lobortis tincidunt massa. Etiam sed tortor eu nulla tincidunt rutrum a et nulla. Suspendisse congue sodales est nec consequat.
<br />
Curabitur at ultricies arcu, non rutrum ipsum. Fusce laoreet ut lorem vel maximus. Aliquam ut lectus gravida, vehicula metus lacinia, pretium mi. Donec ac urna lorem. Praesent placerat, lorem eu semper iaculis, augue arcu finibus massa, non imperdiet dui nisi dictum nunc. Morbi vitae odio a enim eleifend auctor. Etiam vulputate dui sit amet nunc mattis, sit amet condimentum dui tempor. Vivamus elementum nulla libero, id congue sapien ullamcorper sit amet. Ut sed condimentum lorem, ut cursus turpis. Nullam pretium vulputate ipsum ac consequat.
<br />
Aenean cursus laoreet tortor eget auctor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec pretium urna tortor, nec commodo metus suscipit sed. Integer suscipit tincidunt leo, eget egestas nunc tincidunt ac. Praesent sed erat in dolor dignissim mollis. Phasellus placerat tempus justo ac porttitor. Pellentesque imperdiet, orci quis sagittis scelerisque, ipsum lorem iaculis elit, quis rhoncus justo metus nec lorem.
<br />
Donec eu lectus tellus. Duis leo sem, placerat vel metus sed, placerat pharetra metus. Sed a porttitor enim. Maecenas pretium lectus porttitor orci mattis malesuada. Aliquam vehicula sagittis fringilla. Integer at mi ligula. Fusce vitae turpis et metus dictum tempor quis non mi. Vestibulum eros felis, tristique eleifend porttitor vitae, auctor sed erat. Vestibulum feugiat neque eget tellus mollis, sed dictum tellus imperdiet. Vivamus porttitor porta fringilla.
<br />
Suspendisse potenti. Mauris in suscipit risus. Proin id finibus est, ac consectetur velit. In eu dui egestas, pretium neque eget, suscipit ligula. Maecenas faucibus augue at lacinia varius. Proin at gravida tellus, ac ornare sapien. Maecenas imperdiet scelerisque lectus vel iaculis. Donec vehicula, elit vel luctus dapibus, nibh ante malesuada mi, eu pulvinar massa dui sed massa. Integer vitae ultricies elit. Morbi cursus eget magna id dignissim. Nunc in varius ante. Mauris nec commodo velit. Cras feugiat efficitur condimentum.
<br />
Maecenas aliquam, eros vel viverra fermentum, mi massa mattis sem, sit amet fringilla lectus ipsum in odio. Phasellus congue tellus quis ligula malesuada, in dignissim lorem scelerisque. Curabitur lorem risus, mollis eget ligula ac, eleifend gravida erat. Praesent eleifend at diam quis auctor. Sed elementum pretium commodo. Quisque accumsan tortor ac tortor convallis, vitae condimentum risus congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque semper laoreet felis, at dignissim libero blandit sed. Sed varius feugiat urna, id dapibus purus.
<br />
Phasellus porta mauris et enim aliquet, fringilla aliquet nisi commodo. Nulla laoreet dignissim odio vel euismod. Integer bibendum feugiat imperdiet. Nulla ornare pretium mi sed interdum. Donec efficitur, sem vel luctus pharetra, augue augue aliquam sapien, quis mattis nulla nisi eu augue. Integer pulvinar et nulla vitae elementum. Donec dapibus porttitor felis, ac rhoncus massa vestibulum eu. Aenean gravida erat quis purus malesuada eleifend. Suspendisse venenatis est vel arcu pulvinar finibus. Ut a dapibus est. Aliquam sit amet interdum urna. Nulla facilisi. Fusce id neque pharetra ante ornare consectetur. Morbi dapibus arcu maximus erat sagittis gravida.
<br />
Curabitur in est ligula. Nulla sed auctor sapien. Phasellus lobortis massa gravida dui fermentum eleifend. Nulla tincidunt purus quam. Aenean non tortor a nulla pulvinar maximus. Duis iaculis efficitur nisi in volutpat. Cras dignissim nisl condimentum, convallis ipsum eu, pulvinar lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In at hendrerit massa. Proin a leo lacinia, facilisis velit egestas, eleifend justo.
<br />
Aenean finibus, tortor non consequat posuere, purus magna vulputate sapien, ut ullamcorper orci eros vel eros. Nulla faucibus euismod mattis. Aenean justo lacus, rutrum feugiat nunc nec, euismod consequat lorem. Proin egestas cursus metus. Vivamus convallis rutrum nunc, vitae vestibulum sem. Suspendisse dictum ipsum vel leo fringilla, non commodo arcu laoreet. Duis imperdiet euismod magna id facilisis. Proin lobortis, odio sed convallis mattis, libero augue ornare purus, ut mattis diam massa non arcu.
<br />
Cras a auctor felis. Maecenas vel odio eget lacus condimentum gravida vel non magna. Duis gravida quam orci, in consequat felis interdum sed. Proin at imperdiet nibh. Vivamus posuere dui a leo faucibus accumsan. Phasellus dapibus metus ac nisi rhoncus tristique. Mauris quis elementum sem.
<br />
Pellentesque id neque risus. In accumsan venenatis quam vulputate varius. Phasellus sollicitudin nisl ac nisl molestie commodo. Proin mattis, purus ut condimentum aliquet, magna nisi viverra erat, et ultrices purus odio ac ex. Duis cursus odio ac lacinia dapibus. Suspendisse sagittis lacinia consequat. Maecenas dapibus id turpis eu blandit. Phasellus lacinia mi sit amet massa faucibus rhoncus. Praesent ex arcu, iaculis vel tortor elementum, viverra aliquet turpis. Etiam vel posuere diam. Nulla blandit, urna tempor pretium sodales, ex velit vestibulum felis, ut aliquam metus felis quis ligula. Phasellus non tellus sed nisi imperdiet porta.
<br />
Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam rutrum velit mattis, fringilla urna quis, dignissim neque. In hac habitasse platea dictumst. Phasellus rhoncus augue purus, a molestie arcu tincidunt vitae. Vivamus placerat imperdiet dictum. Donec maximus consectetur augue sit amet mattis. Nunc consectetur dolor vel arcu volutpat, gravida consectetur orci dapibus. In hac habitasse platea dictumst. Aenean vitae tellus volutpat ligula dapibus ullamcorper. Praesent sed imperdiet risus.
<br />
Suspendisse potenti. Praesent lobortis purus egestas diam bibendum mollis vel vel nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse metus magna, rhoncus nec euismod quis, vulputate et leo. Integer interdum massa quis pellentesque auctor. Sed ac sapien at est finibus dignissim. Proin pretium ante in vestibulum efficitur. Sed sodales, dui nec consequat maximus, urna massa accumsan nisl, ut dictum enim mi vel purus. Aliquam consectetur tincidunt sapien ac porta.
<br />
In hac habitasse platea dictumst. Duis ornare sem ac neque ullamcorper bibendum. Pellentesque ornare non ex eu facilisis. Phasellus suscipit mollis porta. Nam dui arcu, convallis in est ac, dignissim dapibus sem. In et accumsan leo, eu bibendum felis. Ut ornare orci blandit magna ullamcorper, ut eleifend velit hendrerit. Fusce commodo, massa et tempus elementum, leo nulla imperdiet mauris, id rutrum quam turpis eu ex. Integer dapibus lectus eget neque interdum feugiat. Sed blandit, tellus in varius porta, ligula lectus cursus nisl, vitae sagittis nisl nunc vel ante. Donec non tellus sem. Vivamus arcu libero, ultricies nec tempus a, mattis quis quam. Cras tincidunt fermentum vulputate.
<br />
Cras tellus nulla, fermentum vel dolor sed, dignissim hendrerit nisi. Vivamus blandit, nulla quis posuere efficitur, libero velit bibendum nulla, nec porta augue dui ac enim. Cras sodales, ante vel aliquam egestas, ligula nisl pretium purus, at cursus enim elit viverra arcu. Nunc ac ornare urna, vitae consequat tellus. Vivamus efficitur mauris a ex mattis varius. Suspendisse ut risus eu nibh interdum egestas cursus sit amet nunc. Suspendisse potenti. Aliquam lectus ex, placerat sed risus in, rhoncus hendrerit ligula. Duis vitae lacus mollis nulla egestas facilisis vitae a tellus. Sed luctus egestas leo, at luctus nulla feugiat in. Vivamus et sem eget mi aliquet imperdiet. Etiam semper ipsum at mauris feugiat pulvinar. Donec rhoncus tincidunt felis.
<br />
Suspendisse tortor eros, tempus ut justo sit amet, porttitor feugiat diam. Etiam massa purus, fringilla nec metus sit amet, maximus dignissim nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus non nulla lobortis, iaculis nisl ut, porttitor urna. Praesent orci dui, ultricies at sapien et, facilisis ullamcorper mi. Donec pretium, leo vulputate commodo sollicitudin, libero urna dignissim arcu, id sodales libero dolor sit amet ex. Curabitur iaculis congue mi, sed sagittis nisi posuere non. Vivamus et mi blandit, sollicitudin elit in, luctus nisi. Pellentesque sapien lacus, cursus non convallis hendrerit, suscipit et odio. Nullam nec gravida nisl.
<br />
Phasellus ultricies aliquam nisl ut aliquam. Sed pulvinar ligula in nibh iaculis, dictum maximus ligula porttitor. Ut sagittis risus vitae sapien porta fermentum. Aliquam erat volutpat. Pellentesque fringilla tellus nec convallis placerat. Aenean vitae mollis libero, a ultrices velit. Praesent sed erat mauris. Sed ac turpis at risus pulvinar ultrices non et nisl. In eget feugiat ante, at dictum nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec id nisi ante.
<br />
Nullam id convallis nunc. Proin ullamcorper aliquet arcu, id lobortis turpis efficitur a. Proin eu facilisis libero. Curabitur et mollis sapien. Etiam luctus ante vel eros commodo vulputate. Phasellus mollis turpis in quam pretium elementum. Nulla consectetur ante finibus massa cursus, et euismod sapien faucibus. Aliquam ut metus ac felis condimentum finibus. In faucibus, dui sit amet gravida bibendum, lacus ligula faucibus elit, quis tempus lacus leo id massa. Aenean quis dapibus magna, vitae dapibus purus. Vestibulum in elit nisl. Sed vitae ex sed ligula porta maximus sed sit amet urna. Curabitur aliquam lacus ipsum, at elementum ex venenatis ac. Nunc magna massa, bibendum quis facilisis quis, faucibus id erat. Quisque elementum ultricies lacus, in dictum risus blandit a. Sed feugiat lectus sit amet posuere rutrum.
<br />
Ut dolor nisl, dapibus vitae ex sollicitudin, mollis rutrum magna. Sed at diam tincidunt lectus lobortis volutpat. Sed aliquet lacus ac efficitur pretium. Ut lacinia dolor nec arcu vestibulum venenatis. Proin non ligula vel orci volutpat gravida nec ultrices lectus. Maecenas ut libero diam. Sed efficitur magna a nibh gravida, scelerisque placerat eros bibendum. Sed tempus libero at vulputate porttitor.
<br />
In felis turpis, imperdiet eget elit sed, porttitor vulputate neque. Morbi pellentesque augue suscipit, dapibus lorem vel, efficitur sapien. Nunc efficitur nulla ut tortor luctus, in consequat diam convallis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur consectetur velit sit amet rutrum laoreet. Ut non euismod neque, in vestibulum sem. Donec sed justo eget lacus malesuada gravida.
<br />
Vestibulum posuere, lacus tincidunt luctus pellentesque, nisl quam fermentum sem, maximus imperdiet eros tellus in nunc. Morbi molestie quis nunc sed vulputate. Morbi nec ligula sollicitudin, facilisis massa et, sagittis odio. Etiam eget euismod sem. Quisque vitae lorem dui. Integer a sodales nunc. Duis suscipit placerat turpis eget facilisis. Aliquam finibus leo felis, non molestie diam posuere in. Morbi tempor varius enim. Donec non ipsum augue. Vivamus libero metus, faucibus in condimentum vel, malesuada sed orci. Sed non odio felis. Curabitur a pretium urna. Praesent non ipsum et nisi lacinia pellentesque. Vestibulum non dolor ultrices, bibendum felis eu, finibus enim.
<br />
Maecenas dictum et diam et volutpat. Aliquam luctus hendrerit tortor, sollicitudin euismod quam. Pellentesque neque augue, gravida a ultrices ac, rhoncus ut libero. Mauris ex libero, fermentum eget dolor sed, elementum tincidunt orci. Praesent vestibulum ultricies nunc ac pharetra. Aliquam dictum nisi velit, ac dignissim quam placerat sit amet. In odio est, dapibus in mi sed, ultricies rutrum sapien. Phasellus hendrerit, erat nec mattis laoreet, eros enim tristique erat, sed elementum magna elit at leo. Vivamus sed justo eu ante vulputate ornare. Nulla facilisi.
<br />
Proin non tellus venenatis, egestas enim ut, dapibus lacus. Nullam ipsum tellus, porta in accumsan eget, tincidunt eu elit. Quisque imperdiet risus eget accumsan porta. Vestibulum magna nulla, elementum sit amet ipsum sit amet, vulputate feugiat erat. Sed rutrum tellus nec magna imperdiet, vitae facilisis erat efficitur. Nam sapien velit, laoreet sed metus in, condimentum rutrum orci. Vestibulum in sodales ante, ut ullamcorper sem. Suspendisse potenti.
<br />
Nam iaculis molestie pretium. Suspendisse eleifend tempor nisi, quis pulvinar urna lacinia id. Etiam ultricies feugiat urna nec commodo. Nullam malesuada rutrum nulla ac euismod. Pellentesque at nisi eu nisi feugiat molestie. Maecenas ullamcorper ante sit amet malesuada tincidunt. Donec at nisi laoreet, porta massa vitae, tempus eros. Donec turpis felis, dignissim eu massa et, pretium rutrum eros. Nulla diam erat, dictum sed malesuada non, fermentum et neque. Vestibulum rhoncus orci vel volutpat semper. Aliquam vulputate lacus nec justo dictum, eu vulputate ipsum accumsan. Mauris ut magna tristique, semper nisi in, accumsan diam. Curabitur ac dictum felis. Maecenas efficitur vulputate posuere. Mauris lectus massa, aliquam non commodo et, finibus et justo. In hac habitasse platea dictumst.
<br />
Donec risus mi, suscipit sit amet purus quis, suscipit vehicula lacus. Fusce dignissim, quam sed elementum molestie, dui enim iaculis nisl, at auctor sem tellus sit amet arcu. Phasellus gravida vulputate elit sed accumsan. Vivamus suscipit vitae orci eget faucibus. Nullam massa erat, ullamcorper dapibus eleifend at, malesuada ut augue. Vestibulum purus ipsum, rhoncus sed justo id, ullamcorper commodo ipsum. Nulla nunc tortor, vulputate vitae mi sit amet, consectetur scelerisque libero. Nunc vel eros ut enim mollis lacinia. Maecenas metus mauris, aliquet at magna vitae, malesuada vestibulum tortor. Morbi a bibendum nisl. Donec pharetra massa eu nisi sodales blandit. Maecenas molestie magna sit amet erat condimentum elementum. Sed bibendum risus ut est fringilla, vitae egestas ex tincidunt. Fusce non felis in risus viverra congue sit amet quis orci. Sed in turpis a nisi viverra tincidunt.
<br />
In odio libero, varius sit amet nulla cursus, porttitor lobortis sem. Curabitur ut pretium erat. Duis odio lacus, aliquam id urna vitae, dignissim lobortis arcu. Pellentesque at vestibulum ligula. Aenean a laoreet dui. Duis tincidunt at mi vel hendrerit. Nam risus nunc, rhoncus in egestas a, pulvinar id sem. Morbi consectetur vel neque in suscipit. Duis nisl odio, auctor quis magna et, tempor tincidunt neque. Suspendisse porttitor, nisi posuere elementum luctus, libero eros lacinia dolor, a imperdiet nibh mauris vitae neque. Curabitur orci neque, blandit sed nisi sed, accumsan lacinia magna. Integer at risus dapibus, condimentum risus blandit, porttitor neque. Morbi et tincidunt elit. Etiam id dignissim nulla.
<br />
In varius est eget volutpat vestibulum. Ut non mi sed nunc scelerisque rutrum quis vel ligula. Curabitur sapien eros, pulvinar vitae bibendum non, tristique et diam. Donec ullamcorper metus eu vestibulum mattis. Ut eu aliquam purus. Ut ut felis ac mauris scelerisque pretium. Curabitur viverra elit at quam lobortis, sed vulputate ligula tempor. Sed ullamcorper arcu ante, ac porta nunc semper vel. Curabitur enim augue, egestas in risus id, viverra condimentum nibh. Etiam molestie finibus augue ac sagittis. Etiam et risus vel augue congue elementum. Ut eu maximus ante. Morbi lacinia pretium faucibus.
<br />
Cras aliquam, ante vitae rhoncus mollis, lacus enim tincidunt metus, vitae tincidunt dui nisl eu lorem. Donec metus metus, molestie vitae condimentum in, ornare in enim. Proin in nibh tortor. Morbi vel lacus consequat ipsum consectetur rhoncus. Phasellus hendrerit dapibus dolor, at blandit mi bibendum vel. Vestibulum ut risus sit amet magna tincidunt posuere laoreet non nunc. Donec accumsan vehicula consequat.
<br />
Vestibulum sodales viverra eros at feugiat. Sed at est vitae augue facilisis ornare. Integer sit amet dui aliquet, imperdiet odio in, vehicula odio. Nunc dictum velit nec magna elementum, nec molestie lectus varius. Donec imperdiet porta urna, vitae ultrices diam congue vel. Nullam egestas eget dolor egestas cursus. Phasellus quis semper erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent consectetur ultrices turpis eu elementum. Curabitur aliquam justo non facilisis viverra. Proin nec cursus velit. Etiam condimentum felis est. Sed id volutpat magna, at aliquam nibh. Nam faucibus libero id tellus efficitur, nec fringilla dolor maximus. Fusce volutpat euismod elit ac consectetur. Aenean vitae egestas ipsum.
<br />
In hac habitasse platea dictumst. Aliquam bibendum luctus lacus, ac imperdiet nulla gravida at. Morbi ac luctus ligula, ut dignissim urna. Suspendisse eget nisi scelerisque, blandit leo sit amet, pretium sapien. Etiam nibh urna, pharetra id ligula sed, pharetra porttitor neque. Ut ut augue arcu. Aenean malesuada sed dolor lobortis laoreet. Quisque eu tellus eu ex tristique laoreet fringilla vitae tellus. Nunc congue vel felis quis sodales. Praesent in nisi ac est commodo feugiat. Sed pulvinar sodales purus sit amet eleifend. Morbi id condimentum nulla. In ultricies velit nec blandit consequat. Donec quam velit, faucibus vitae tortor ut, tincidunt tempor arcu.
<br />
Praesent ac ornare urna. Vestibulum vitae dictum enim. Vivamus quis risus consectetur, varius sapien vitae, volutpat libero. Mauris dapibus nibh vel leo efficitur condimentum. Morbi euismod mi sed enim blandit pulvinar. Aenean rhoncus, ante sit amet fringilla vehicula, quam tortor mollis libero, a sodales leo risus et dui. Etiam id lorem sit amet nulla gravida scelerisque. Nunc dictum quam quis felis porttitor mollis. Curabitur id massa laoreet, pellentesque lectus sed, viverra diam. Maecenas in turpis molestie, molestie erat iaculis, mollis ante.
<br />
Morbi pellentesque vitae eros euismod aliquam. In eleifend hendrerit aliquam. Integer vitae justo sit amet eros laoreet facilisis suscipit et urna. Quisque eget nunc at leo dignissim consectetur et sit amet diam. Nullam interdum pretium tortor, et ultricies diam euismod id. Fusce non magna nec nulla fermentum congue at eu mi. Fusce ultrices ac velit et auctor.
<br />
Pellentesque posuere consequat eros, id posuere mi pellentesque et. Praesent eget tortor vel diam egestas ornare. Nam dolor massa, porta sit amet vehicula eget, dapibus ut mauris. Sed quam neque, commodo vel ligula vel, vestibulum fringilla tellus. Ut congue pellentesque eros vulputate tincidunt. Cras at rutrum metus. Vivamus sem arcu, rhoncus at elementum luctus, tincidunt quis sem. Curabitur ultricies, libero vel feugiat sagittis, diam nunc viverra diam, sit amet egestas felis lectus scelerisque ex.
<br />
Suspendisse eros sapien, placerat ac diam eget, volutpat congue erat. Aenean mollis gravida ligula, et convallis purus vestibulum sed. Donec sed turpis arcu. Sed a risus sagittis, blandit lacus quis, placerat diam. Praesent tristique lobortis orci, eget molestie massa. Vivamus augue mauris, vulputate ac sodales at, commodo vitae neque. Morbi quis convallis risus, vel egestas velit. Phasellus eget rutrum ligula. Nunc tempus elit a augue euismod ultricies. Mauris sagittis vitae tellus vel dictum. Nullam viverra, massa ut euismod mollis, orci leo volutpat lectus, vitae feugiat ipsum purus pellentesque turpis. Mauris consequat tortor et ipsum sollicitudin, eget euismod tellus venenatis. Ut scelerisque pulvinar orci, sed finibus enim laoreet et. Sed ut sapien ornare, fringilla lorem eget, tristique dui. Integer dui neque, pulvinar quis massa vel, laoreet euismod nisi. Curabitur ac fringilla quam.
<br />
Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis posuere mauris quam, ac mattis nulla congue nec. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean dapibus rhoncus felis. Nulla placerat mauris nulla. Nullam fringilla a nisl at pretium. Cras scelerisque commodo volutpat. Curabitur id dolor eu purus eleifend rutrum eget vel mi. Etiam eget neque feugiat ipsum accumsan luctus scelerisque eu magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum auctor iaculis bibendum. Nam sodales suscipit nunc, sed consequat felis hendrerit ac.
<br />
Aliquam et lectus porttitor, rhoncus eros et, bibendum ipsum. Ut placerat nunc eget leo fringilla interdum. Pellentesque ullamcorper, leo eget condimentum commodo, ipsum lacus gravida quam, eget semper nunc ligula a tellus. Praesent in felis aliquam, ornare risus non, faucibus arcu. Morbi ut quam euismod, feugiat sapien vel, tincidunt magna. Praesent vestibulum turpis ac arcu accumsan, sollicitudin luctus orci faucibus. Pellentesque nec consectetur mauris. Nullam aliquam pharetra sapien ac egestas. Quisque dolor enim, ultricies in dui vel, ultricies tempor lacus. Maecenas ac aliquet nulla, non consequat enim. Integer vulputate mi ex, eu tincidunt tortor tristique non.
`;


const body = document.querySelector('body');
body.append(texto);

const progressBar = document.createElement('div');
progressBar.setAttribute('class', 'progress-bar');
body.append(progressBar);

const calcularPorcentajeScroll = (event) => {
    const {
        scrollTop,
        scrollHeight,
        clientHeight
    } = event.target.documentElement;
    return (scrollTop / (scrollHeight - clientHeight) ) * 100;
}

const scroll$ = fromEvent(document, 'scroll').pipe(
    map( calcularPorcentajeScroll),
    tap( console.log )
);
scroll$.subscribe(porcentaje => {
    progressBar.style.width = `${ porcentaje }%`;
});